### ISSUE TITLE
cmake文件无法找到Qt5QuickWidgets库

### ISSUE THREAD

**Issue by ellicefix** [fcitx/fcitx5-qt#1]
Qt5QuickWidgets已经安装：

库文件在：

/usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.so

但是 cmake 时，报错如下

***********

:~/Downloads/fcitx5-qt-master/build$ cmake ..
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Found XCB_XCB: /usr/lib/x86_64-linux-gnu/libxcb.so (found version "1.12") 
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so (found version "1.12") found components:  XCB 
-- Found XKBCommon_XKBCommon: /usr/lib/x86_64-linux-gnu/libxkbcommon.so (found version "0.7.1") 
-- Found XKBCommon: /usr/lib/x86_64-linux-gnu/libxkbcommon.so (found suitable version "0.7.1", minimum required is "0.5.0") found components:  XKBCommon 
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake-qt4 (found suitable version "4.8.7", minimum required is "4.8.0") 
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:26 (find_package):
  Could not find a package configuration file provided by "Qt5QuickWidgets"
  with any of the following names:

    Qt5QuickWidgetsConfig.cmake
    qt5quickwidgets-config.cmake

  Add the installation prefix of "Qt5QuickWidgets" to CMAKE_PREFIX_PATH or
  set "Qt5QuickWidgets_DIR" to a directory containing one of the above files.
  If "Qt5QuickWidgets" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:54 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/lin/Downloads/fcitx5-qt-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/lin/Downloads/fcitx5-qt-master/build/CMakeFiles/CMakeError.log".

**Comment by ellicefix** [comment]
尝试失败：

$ cmake ..--CMAKE_PREFIX_PATH="/usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.so"

CMake Error: 
The source directory "/home/lin/Downloads/fcitx5-qt-master/build/..--CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.so" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by wengxt** [comment]
…姿势不对

你为什么要自己编译这个… -DCMAKE_INSTALL_PREFIX=XXXX

……我不负责教你用 cmake。

不过上游已经合并了我的修复了这个 qquickwidgets 的 hack 我可以去掉了。另外这个是给 fcitx5 用的
