### ISSUE TITLE
Is there a bug? Maybe Impress in Libreoffice conflicts with fcitx5-qt.

### ISSUE THREAD

**Issue by open-src** [fcitx/fcitx5-qt#15]
I'm a fcitx5 user on Manjaro and loves this wonderful input method application, but Maybe there is a bug in it.
When I opened a libreoffice-impress document, and clicked some text box or input some words, and made impress to lose its focus(such as switching to another application), and clicked some text box in Impress again(that is to say, gained the focus again), impress crashes.

--------------------------------------
The issue also exists in fcitx-qt5，but it did not occur when I downgraded fcitx-qt5 from 1.2.5 to 1.2.4.

I'm using KF5 on Manjaro 20.1.1.

**Comment by wengxt** [comment]
I think it's fixed by 97ea203b406849328d14918e135985ef64e1031b
