### ISSUE TITLE
如何将fcitx5-qt集成到Qt应用，实现程序自动切换输入法，和知道当前输入法？

### ISSUE THREAD

**Issue by diricse** [fcitx/fcitx5-qt#19]
如何将fcitx5-qt集成到Qt应用，实现程序自动切换输入法，和知道当前输入法？

**Comment by wengxt** [comment]
首先并没有提供访问「某个程序」输入法的方式，只有一个可以访问目前程序输入法的方式

https://github.com/fcitx/fcitx5-qt/blob/ddc2214b36b3199f071efffe8db1d1613c5e1e1a/qt5/dbusaddons/fcitxqtcontrollerproxy.h#L95

不使用这个库也可以简单办到，就是调用 dbus 而已。
例如只是执行命令的话
qdbus org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.CurrentInputMethod
啊…方法名字不太一致我很抱歉……因为有的是沿用当初 fcitx4 的后来就忘记统一了…
qdbus org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.SetCurrentIM pinyin

**Comment by diricse** [comment]
谢谢
