### ISSUE TITLE
can't use fcitx5 in qtcreator

### ISSUE THREAD

**Issue by nooly1998** [fcitx/fcitx5-qt#28]
I can't use fcitx5 to input Chinese in QtCreator, but fcitx5 can use in other programs.

Manjaro KDE
Qt Version: 5.15.2
use KDE 5.23.4, KDE framwork 5.89.0

readlink("/home/weiminghao/Qt/Tools/QtCreator/lib/Qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so", 0x7ffd356bb450, 1023) = -1 EINVAL
openat(AT_FDCWD, "/home/weiminghao/Qt/Tools/QtCreator/lib/Qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6
readlink("/home/weiminghao/Qt/Tools/QtCreator/lib/Qt/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so", 0x7ffd356bb450, 1023) = -1 EINVAL
openat(AT_FDCWD, "/home/weiminghao/Qt/Tools/QtCreator/lib/Qt/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6

**Comment by wengxt** [comment]
I suggest you use qtcreator from repo, so it can use system Qt.

If you just copy a random plugin into it, it may not load due to different qt version.

**Comment by xingwozhonghua** [comment]
> I can't use fcitx5 to input Chinese in QtCreator, but fcitx5 can use in other programs.
> 
> Manjaro KDE Qt Version: 5.15.2 use KDE 5.23.4, KDE framwork 5.89.0
> 
> readlink("/home/weiminghao/Qt/Tools/QtCreator/lib/Qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so", 0x7ffd356bb450, 1023) = -1 EINVAL openat(AT_FDCWD, "/home/weiminghao/Qt/Tools/QtCreator/lib/Qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6 readlink("/home/weiminghao/Qt/Tools/QtCreator/lib/Qt/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so", 0x7ffd356bb450, 1023) = -1 EINVAL openat(AT_FDCWD, "/home/weiminghao/Qt/Tools/QtCreator/lib/Qt/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6

QtCreater 输入中文的问题，

下面是针对fcitx-qt5的fcitx5-qt也是一样的。

```
#!/bin/bash

CMD_PATH=`dirname $0`
userdir=`env | grep ^HOME= | cut -c 6-`

qt5Creator=${userdir}/Qt5.14.2/Tools/QtCreator/lib/Qt/plugins/platforminputcontexts
qt5gcc_64=${userdir}/Qt5.14.2/5.14.2/gcc_64/plugins/platforminputcontexts
export Qt5_DIR=${userdir}/Qt5.14.2/5.14.2/gcc_64/lib/cmake/Qt5

//sudo apt install git
//git clone http://github.com/fcitx/fcitx-qt5.git
apt source fcitx-qt5


rm -r  ~/fcitx-qt5/build
mkdir ~/fcitx-qt5/build
cd    ~/fcitx-qt5/build

sudo apt install gcc g++ cmake extra-cmake-modules
sudo apt install libgl1-mesa-dev libglu1-mesa-dev libxkbcommon-dev fcitx-libs-dev

cmake ../
make

libfcix=~/fcitx-qt5/build/platforminputcontext/libfcitxplatforminputcontextplugin.so

sudo cp $libfcix ${qt5Creator}
sudo cp $libfcix ${qt5gcc_64}
sudo chmod +x  ${qt5Creator}/libfcitxplatforminputcontextplugin.so
sudo chmod 777 ${qt5Creator}/libfcitxplatforminputcontextplugin.so
sudo chmod +x  ${qt5gcc_64}/libfcitxplatforminputcontextplugin.so
sudo chmod 777 ${qt5gcc_64}/libfcitxplatforminputcontextplugin.so
```


```
#!/bin/bash

userdir=`env | grep ^HOME= | cut -c 6-`
qt5Creator=${userdir}/Qt5.14.2/Tools/QtCreator/lib/Qt/plugins/platforminputcontexts
qt5gcc_64=${userdir}/Qt5.14.2/5.14.2/gcc_64/plugins/platforminputcontexts
```

# 静态库文件

```
libfcix=~/fcitx-qt5/build/platforminputcontext/libfcitx5platforminputcontextplugin.so

sudo cp $libfcix ${qt5Creator}
sudo cp $libfcix ${qt5gcc_64}
sudo chmod +x  ${qt5Creator}/libfcitx5platforminputcontextplugin.so
sudo chmod 777 ${qt5Creator}/libfcitx5platforminputcontextplugin.so
sudo chmod +x  ${qt5gcc_64}/libfcitx5platforminputcontextplugin.so
sudo chmod 777 ${qt5gcc_64}/libfcitx5platforminputcontextplugin.so
```

**Comment by nooly1998** [comment]
I have installed fcitx5 and compiled fcitx5-qt, and I have copied this .so file to the location you mentioned and given execute permissions. But QtCreator still can't use fctx5 to enter Chinese.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月9日(星期天) 晚上10:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fcitx/fcitx5-qt] can&#39;t use fcitx5 in qtcreator (Issue #28)





  
I can't use fcitx5 to input Chinese in QtCreator, but fcitx5 can use in other programs.
 
Manjaro KDE Qt Version: 5.15.2 use KDE 5.23.4, KDE framwork 5.89.0
 
readlink("/home/weiminghao/Qt/Tools/QtCreator/lib/Qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so", 0x7ffd356bb450, 1023) = -1 EINVAL openat(AT_FDCWD, "/home/weiminghao/Qt/Tools/QtCreator/lib/Qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6 readlink("/home/weiminghao/Qt/Tools/QtCreator/lib/Qt/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so", 0x7ffd356bb450, 1023) = -1 EINVAL openat(AT_FDCWD, "/home/weiminghao/Qt/Tools/QtCreator/lib/Qt/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6
  
QtCreater 输入中文的问题，
 
下面是针对fcitx-qt5的fcitx5-qt也是一样的。
 #!/bin/bash CMD_PATH=`dirname $0` userdir=`env | grep ^HOME= | cut -c 6-` qt5Creator=${userdir}/Qt5.14.2/Tools/QtCreator/lib/Qt/plugins/platforminputcontexts qt5gcc_64=${userdir}/Qt5.14.2/5.14.2/gcc_64/plugins/platforminputcontexts export Qt5_DIR=${userdir}/Qt5.14.2/5.14.2/gcc_64/lib/cmake/Qt5 //sudo apt install git //git clone http://github.com/fcitx/fcitx-qt5.git apt source fcitx-qt5 rm -r  ~/fcitx-qt5/build mkdir ~/fcitx-qt5/build cd    ~/fcitx-qt5/build sudo apt install gcc g++ cmake extra-cmake-modules sudo apt install libgl1-mesa-dev libglu1-mesa-dev libxkbcommon-dev fcitx-libs-dev cmake ../ make libfcix=~/fcitx-qt5/build/platforminputcontext/libfcitxplatforminputcontextplugin.so sudo cp $libfcix ${qt5Creator} sudo cp $libfcix ${qt5gcc_64} sudo chmod +x  ${qt5Creator}/libfcitxplatforminputcontextplugin.so sudo chmod 777 ${qt5Creator}/libfcitxplatforminputcontextplugin.so sudo chmod +x  ${qt5gcc_64}/libfcitxplatforminputcontextplugin.so sudo chmod 777 ${qt5gcc_64}/libfcitxplatforminputcontextplugin.so  #!/bin/bash userdir=`env | grep ^HOME= | cut -c 6-` qt5Creator=${userdir}/Qt5.14.2/Tools/QtCreator/lib/Qt/plugins/platforminputcontexts qt5gcc_64=${userdir}/Qt5.14.2/5.14.2/gcc_64/plugins/platforminputcontexts  
静态库文件
 libfcix=~/fcitx-qt5/build/platforminputcontext/libfcitx5platforminputcontextplugin.so sudo cp $libfcix ${qt5Creator} sudo cp $libfcix ${qt5gcc_64} sudo chmod +x  ${qt5Creator}/libfcitx5platforminputcontextplugin.so sudo chmod 777 ${qt5Creator}/libfcitx5platforminputcontextplugin.so sudo chmod +x  ${qt5gcc_64}/libfcitx5platforminputcontextplugin.so sudo chmod 777 ${qt5gcc_64}/libfcitx5platforminputcontextplugin.so  
&mdash;

**Comment by yuyichao** [comment]
Compiling things like so will not help you if there's a version mismatch. For one, it's clear that you are not using qt 5.14.2 (assuming this is the qt version used by qt creator).

**Comment by wengxt** [comment]
If you really interested in how to do that properly, you can read: https://www.csslayer.info/wordpress/fcitx-dev/a-case-study-how-to-compile-a-fcitx-platforminputcontext-plugin-for-a-proprietary-software-that-uses-qt-5/

At the same time, since you're using manjaro anyway, why not just `pacman -S qtcreator`?

As an alternative method, you can also use fcitx5's ibus frontend. QT_IM_MODULE=ibus ./qtcreator should also work for you.
