### ISSUE TITLE
Fcitx5UtilsConfig.cmake请问这是缺什么

### ISSUE THREAD

**Issue by zhanghaiwen12** [fcitx/fcitx5-qt#31]
CMake Error at CMakeLists.txt:33 (find_package):
  By not providing "FindFcitx5Utils.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Fcitx5Utils", but CMake did not find one.
fcitx5 安装了

  Could not find a package configuration file provided by "Fcitx5Utils" with
  any of the following names:

    Fcitx5UtilsConfig.cmake
    fcitx5utils-config.cmake

  Add the installation prefix of "Fcitx5Utils" to CMAKE_PREFIX_PATH or set
  "Fcitx5Utils_DIR" to a directory containing one of the above files.  If
  "Fcitx5Utils" provides a separate development package or SDK, be sure it
  has been installed.
-- Configuring incomplete, errors occurred!
See also "/home/vpn/workplace/fcitx/fcitx5-qt-75/CMakeFiles/CMakeOutput.log".

**Comment by wengxt** [comment]
我知道你是想编译静态库，参数传 -DBUILD_ONLY_PLUGIN=On -DBUILD_STATIC_PLUGIN=On

编译全套需要安装 fcitx5 的开发文件。请根据你的发行版自己查找，名称多半有 -dev -devel

**Comment by zhanghaiwen12** [comment]
引用这个生成的.a报错了
编译cmake -DENABLE_QT4=Off -DBUILD_ONLY_PLUGIN=On -DBUILD_STATIC_PLUGIN=On .

Q_IMPORT_PLUGIN(QFcitx5PlatformInputContextPlugin)
Q_IMPORT_PLUGIN(QComposePlatformInputContextPlugin)
Q_IMPORT_PLUGIN(QIbusPlatformInputContextPlugin)

LIBS +=/opt/qt_5.15.2/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.a
LIBS +=/opt/qt_5.15.2/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.a
LIBS +=/opt/qt_5.15.2/plugins/platforminputcontexts/libibusplatforminputcontextplugin.a

编译项目报错

/opt/qt_5.15.2/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.a(qfcitxplatforminputcontext.cpp.o)：在函数‘fcitx::QFcitxPlatformInputContext::QFcitxPlatformInputContext()’中：
qfcitxplatforminputcontext.cpp:(.text+0x488)：对‘fcitx::FcitxQtWatcher::FcitxQtWatcher(QDBusConnection const&, QObject*)’未定义的引用
qfcitxplatforminputcontext.cpp:(.text+0x625)：对‘fcitx::registerFcitxQtDBusTypes()’未定义的引用
qfcitxplatforminputcontext.cpp:(.text+0x63a)：对‘fcitx::FcitxQtWatcher::setWatchPortal(bool)’未定义的引用
qfcitxplatforminputcontext.cpp:(.text+0x64a)：对‘fcitx::FcitxQtWatcher::watch()’未定义的引用
/opt/qt_5.15.2/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.a(qfcitxplatforminputcontext.cpp.o)：在函数‘fcitx::QFcitxPlatformInputContext::~QFcitxPlatformInputContext()’中：
qfcitxplatforminputcontext.cpp:(.text+0x7a7)：对‘fcitx::FcitxQtWatcher::unwatch()’未定义的引用
/opt/qt_5.15.2/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.a(qfcitxplatforminputcontext.cpp.o)：在函数‘fcitx::QFcitxPlatformInputContext::reset()’中：
qfcitxplatforminputcontext.cpp:(.text+0xc16)：对‘fcitx::FcitxQtInputContextProxy::reset()’未定义的引用
/opt/qt_5.15.2/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.a(qfcitxplatforminputcontext.cpp.o)：在函数‘fcitx::QFcitxPlatformInputContext::update(QFlags<Qt::InputMethodQuery>)’中：
qfcitxplatforminputcontext.cpp:(.text+0x1880)：对‘fcitx::FcitxQtInputContextProxy::setSurroundingText(QString const&, unsigned int, unsigned int)’未定义的引用
qfcitxplatforminputcontext.cpp:(.text+0x18bc)：对‘fcitx::FcitxQtInputContextProxy::setSurroundingTextPosition(unsigned int, unsigned int)’未定义的引用

**Comment by zhanghaiwen12** [comment]
编 fcitx-qt5的静态版,是吧所有cmakelist的module改为static吗
引用fcitx5-qt.a在fcitx 4.2.9.1环境中无效，在fcitx version: 4.2.9.32.5中 发生键盘事件后，程序段错误闪退。

编译cmake -DENABLE_QT4=Off -DBUILD_ONLY_PLUGIN=On -DBUILD_STATIC_PLUGIN=On .

在mian.cpp中 
#include <QtPlugin>
Q_IMPORT_PLUGIN(QFcitxPlatformInputContextPlugin)

在pro中
LIBS +=/opt/qt_5.15.2/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.a
LIBS +=/opt/qt_5.15.2/plugins/platforminputcontexts/libFcitx5Qt5DBusAddons.a

**Comment by wengxt** [comment]
fcitx-qt5 又没有支持，怎么改能用那是你自己的事了

fcitx5-qt 你可以参考如下配置
```
Q_IMPORT_PLUGIN(QFcitx5PlatformInputContextPlugin);
```

```
QT       += core gui dbus

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    main.cpp \
    mainwindow.cpp

HEADERS += \
    mainwindow.h

FORMS += \
    mainwindow.ui

LIBS += \
    /home/csslayer/Develop/build/fcitx5-qt/build/qt5/platforminputcontext/libfcitx5platforminputcontextplugin.a \
    /home/csslayer/Develop/build/fcitx5-qt/build/qt5/dbusaddons/libFcitx5Qt5DBusAddons.a \
    -lxcb -lxkbcommon
```
