### ISSUE TITLE
Font fallback

### ISSUE THREAD

**Issue by xsrvmy** [fcitx/fcitx5-qt#32]
When typing with fcitx5 IME in a qt application, if a character is not in the font set from the fcitx5 settings, I get a tofu. When the same happens in a gtk application, the character falls back to a different font without this problem. I also don't get colored emoji's either.

Is this repo the source of the problem? Or is it just QT's fallback mechanism causing issues?

Should clarify that I am on wayland.

**Comment by wengxt** [comment]
While you're using wayland, you're most likely using the input panel rendered by qt with in the application.

With that being said. ![图片](https://user-images.githubusercontent.com/259684/168411333-823470ab-d67f-4745-a159-902570cf4ffd.png)
I certainly can get colored emoji in qt, even if I selected some other font like dejavu but using noto emoji.

What's your font in the configuration?

**Comment by xsrvmy** [comment]
I am using a weirder Chinese font (LXGW)
Maybe I just need to set things up in font-config. GTK actually is able to figure out the font fallback on it's own.

**Comment by wengxt** [comment]
I tried some custom qt font and get same behavior.

not fcitx5-qt's problem.
