### ISSUE TITLE
Candidate window on 2x HiDPI screen is stretched 2x with Qt 6.5 and KWin 5.27

### ISSUE THREAD

**Issue by hexchain** [fcitx/fcitx5-qt#38]
Fcitx5's candidate window starts appearing overly large and blurry after wayland fractional scaling is supported by both Qt and KWin:

![image](https://user-images.githubusercontent.com/529520/215996360-f3f7a8ee-b458-4d14-9d73-13187633c7f9.png)

This is Qt 6.5.0b2 on KWin 5.26.90, on a 4K 200% HiDPI screen. If I disable fractional scaling support in KWin (by commenting out the `new FractionalScaleManagerV1Interface` line in kwin/src/wayland_server.cpp), the candidate window size returns to normal.

**Comment by wengxt** [comment]
is this client side input panel, or zwp_input_method_v1?

**Comment by hexchain** [comment]
The window comes from `fcitxcandidatewindow.cpp` (I've done some print debugging to confirm that), so I guess it is the client-side input panel.
