### ISSUE TITLE
fcitx5-qt (5.1.0) causes "QSocketNotifier: Can only be used with threads started with QThread" error in KDE wayland session

### ISSUE THREAD

**Issue by pengshao** [fcitx/fcitx5-qt#46]
Hi, I recently upgraded fcitx5-qt on my Arch linux KDE wayland PC (5.0.17 => 5.1.0) and I immediately ran into issue that when running any QT based applications in terminal it throws the error message as mentioned above:

```
[dev@localhost ~]$ ksshaskpass -v           
QSocketNotifier: Can only be used with threads started with QThread
ksshaskpass 5.27.7
```

Downgrading it to 5.0.17 yields correct output
```
[dev@localhost ~]$ ksshaskpass -v           
ksshaskpass 5.27.7
```

This bug is impacting all qt5 based applications when running from terminal. Worst impacting being ksshaskpass when running throws this error for all git commands and broke some of my workflow which relies on git's clean output without this error. Given the wide impacting of this bug to those who use fcitx (mostly East Asian users I believe) if the fix can be prioritized that would be greatly appreciated. :)

**This bug seems to have only impacted wayland session.**

Thanks for taking a look in advance.

**Comment by kingysu** [comment]
@pengshao 很有可能
