### ISSUE TITLE
Unable to build: error: 'unique_ptr' in namespace 'std' does not name a template type

### ISSUE THREAD

**Issue by poscat0x04** [fcitx/fcitx5-qt#5]
Build log: https://fars.ee/JE4Q
nix expression: https://fars.ee/SphZ

Trying to port fcitx5 to nixpkgs, any idea why this failed?

**Comment by qiankun3** [comment]
在某个头文件加入#include <memory>

**Comment by kebugcheckex** [comment]
I have the same issue. Add `#include <memory>` to `qt5/platforminputcontext/qfcitxplatforminputcontext.h` fixes the problem. However, I don't know why others don't run into this problem.
