### ISSUE TITLE
QT_WAYLAND_FORCE_DPI breaks fcitx5's input window rendering

### ISSUE THREAD

**Issue by lilydjwg** [fcitx/fcitx5-qt#55]
I'm on Wayfire wayland and display scale=1. I want to set QT_WAYLAND_FORCE_DPI=120 for larger text because some important applications still don't support or have broken support for wayland's native fractional scale. However, it breaks fcitx5's input window rendering (position is wrong, and window cropped like Firefox's popups with fractional scale):

![图片](https://github.com/fcitx/fcitx5-qt/assets/440661/f8709b49-e9e1-4675-8fae-6cb33044fd4d)

It happens for Telegram and Wireshark which use Qt6. It doesn't happen for fcitx5-configtool which uses Qt5.

**Comment by wengxt** [comment]
@lilydjwg I can't reproduce this under kwin . Do you have some other exact step to reproduce this?
 QT_IM_MODULE=fcitx QT_WAYLAND_FORCE_DPI=120 telegram-desktop 

Also I don't see QT_WAYLAND_FORCE_DPI=120  do anything to telegram

**Comment by lilydjwg** [comment]
I can reproduce with `QT_IM_MODULE=fcitx QT_WAYLAND_FORCE_DPI=120 wireshark` on KDE with a new user in my virtual machine (telegram is not logged in there).

Telegram doesn't need it. fcitx5 needs it to have larger text.
