### ISSUE TITLE
fcitx5-configtool does not run without qt5-x11extras

### ISSUE THREAD

**Issue by btchinainfo** [fcitx/fcitx5-qt#9]
After the commit of https://github.com/fcitx/fcitx5-qt/commit/47628ac9f81b589d8e69f82b121d08773b06e813, 
the qt5-x11extras has been removed from my system (archlinux+xfce), cause it does not depended by any other packages.
But in this case, fcitx5-configtool will not run corectly  by missing libQt5X11Extras.so.5.

$ fcitx5-configtool
fcitx5-config-qt: error while loading shared libraries: libQt5X11Extras.so.5: cannot open shared object file: No such file or directory

**Comment by wengxt** [comment]
packager issue.
